version: '3.7'

services:
  web:
    container_name: "xreact"
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
#    volumes:
#      - /app/node_modules
#      - .:/app